version: '3.8'

services:

  elasticsearch:
    image: elasticsearch:8.4.2
    container_name: elasticsearch
    ports:
      - 9200:9200
    environment:      
      ES_JAVA_OPTS: -Xms1g -Xmx1g
      ELASTIC_PASSWORD: StrongPassw0rd1
    networks:
      - elk

  kibana:
    image: kibana:8.4.2
    container_name: kibana
    environment:
      KIBANA_SYSTEM_PASSWORD: StrongPassw0rd1
      ELASTICSEARCH_HOSTS: '["https://localhost:9200"]'
    networks:
      - elk
    ports:
      - 5601:5601

networks:
  elk:
    driver: bridge