version: '3.8'

services:

  elasticsearch:
    image: elasticsearch:8.4.2
    container_name: elasticsearch
    environment:
      ELASTIC_PASSWORD: Ch@ngMe
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      discovery.type: single-node
    volumes:
      - elastic:/usr/share/elasticsearch/data
    networks:
      - elastic

  kibana:
    image: kibana:8.4.2
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      KIBANA_SYSTEM_PASSWORD: Ch@ngeMe
      ELASTICSEARCH_HOSTS: "[https://elasticsearch:9200]"
    networks:
      - elastic
    ports:
      - 5601:5601

networks:
  elastic:
    driver: bridge
volumes:
  elastic: