apiVersion: v1
kind: Pod
metadata:
  name: business-app
  labels:
    name: business-app
spec:
  containers:
  - name: business-app
    image: nginx:1.21-alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80

---

apiVersion: v1
kind: Binding
metadata:
  name: nginx
target:
  apiVersion: v1
  kind: Node
  name: node