apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-app
  labels:
    app: App1
    functionality: backend
  annotations:
    mycompanyname.relevant.info: "my-app"
spec:
  selector:
    matchLabels:
      app: business-app
  template:
    metadata:
      labels:
        app: business-app
    spec:
      containers:
      - name: business-app
        image: nginx:1.21-alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
