apiVersion: v1
kind: Pod
metadata:
  name: business-app

  # Labels
  labels:
    name: business-app
    function: backend

spec:
  containers:
  - name: business-app
    image: nginx:1.21-alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-app
  # Labels related to the deployment
  type: deployment
  functionality: backend

spec:
  selector:
    matchLabels:
      app: business-app
  template:
    metadata:
      # Labels related to the Pod
      labels:
        app: business-app
        type: pod
    spec:
      containers:
      - name: business-app
        image: nginx:1.21-alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
