apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-app
spec:
  selector:
    matchLabels:
      app: server-app
  template:
    metadata:
      labels:
        app: server-app
    spec:
      affinity:
        nodeAffinity:
          
      containers:
      - name: server-app
        image: nginx:1.21-alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
