# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_NO_PARALLEL'] = 'yes'

MASTER_COUNT = 1
IMAGE = "bento/ubuntu-22.04"
BOX_VERSION = "v202206.13.0"
MEMORY_MASTER = 1024
CPUS_MASTER = 1

WORKER_COUNT = 2
MEMORY_WORKER = 1024
CPUS_WORKER = 1

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"


  # Kubernetes Master Nodes

  (1..MASTER_COUNT).each do |i|

    config.vm.define "kmaster#{i}" do |masternode|

      masternode.vm.box               = IMAGE
      masternode.vm.box_check_update  = false
      masternode.vm.box_version       = BOX_VERSION
      masternode.vm.hostname          = "master#{i}.example.com"

      masternode.vm.network "private_network", ip: "172.16.16.10#{i}"

      masternode.vm.provider :virtualbox do |v|
        v.name   = "master0#{i}"
        v.memory = MEMORY_MASTER
        v.cpus   = CPUS_MASTER
      end
    

    end

  end

  
  (1..WORKER_COUNT).each do |i|

    config.vm.define "kworker#{i}" do |workernode|

      workernode.vm.box               = IMAGE
      workernode.vm.box_check_update  = false
      workernode.vm.box_version       = BOX_VERSION
      workernode.vm.hostname          = "worker#{i}.example.com"

      workernode.vm.network "private_network", ip: "172.16.16.20#{i}"

      workernode.vm.provider :virtualbox do |v|
        v.name   = "worker#{i}"
        v.memory = MEMORY_WORKER
        v.cpus   = CPUS_WORKER
      end

    end

  end

end
