apiVersion: v1
kind: Pod
metadata:
  name: business-app
  labels:
    name: business-app
spec:
  volumes:
    - name: logs-data
      hostPath:
        path: /data
  containers:
  - name: business-app
    image: nginx:1.21-alpine
    volumeMounts:
      - name: logs-data
        mountPath: /var/log/nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
