apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: myOpensearch
spec:
  selector:
    matchLabels:
      app: opensearch-app
  serviceName: opensearch-srv
  replicas: 2
  template:
    metadata:
      labels:
        app: opensearch-app
    spec:
      containers:
      - name: opensearch-app
        image: opensearchproject/opensearch:2.3.0
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
