apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seaweedfs
spec:
  storageClassName: "seaweedfs-storage"
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

---

apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  volumes:
    - name: "myvolume"
      persistentVolumeClaim:
        claimName: seaweedfs
  containers:
  - name: myapp
    image: busybox

    volumeMounts:
      - mountPath: "/root/data"
        name: "myvolume"
    command: ["/bin/sh"]
    args: ["-c", while true; do date >> /root/data/myfile.txt; sleep 5; done]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"

