apiVersion: batch/v1
kind: Job
metadata:
  name: sleepy
spec:
  ttlSecondsAfterFinished: 100
  completions: 5
  parallelism: 1
  backoffLimit: 5
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["/bin/sleep"]
        args:
          - "3"
      restartPolicy: Never
