apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: myapp
    image: nginx:1.21-alpine

    # container resources
    resources:
      # Maximun resource to take
      limits:
        memory: "128Mi"
        cpu: "500m"
      # Minimun resources to take
      requests:
        cpu: "0.25"
        memory: "64Mi"
    ports:
      - containerPort: 80
  
  # Sidecar container
  - name: sidecar-app
    image: alpine:3.14
    resources:
      # Maximun resource to take
      limits:
        memory: "128Mi"
        cpu: "500m"
      # Minimun resources to take
      requests:
        cpu: "0.25"
        memory: "64Mi"
  # Containers that will start earlier
  initContainers:
    - name: first-container
      image: busybox
      command: ['sh', '-c', 'sleep 5']

    